<a href="https://colab.research.google.com/github/Anilir/MyReport/blob/main/middle_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
strText = input("아무 문장이나 입력하세요 : ")
print(strText)

테스트


In [ ]:
flVal = [1.0, 2.0, 3.14, 4.2, 5.1]

In [ ]:
arVal = [flVal, flVal, flVal]
arVal

[[1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1],
 [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
arVal[0]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [ ]:
arVal[1]

[1.0, 2.0, 3.14, 4.2, 5.1]

In [ ]:
arVal[1][2]

3.14

In [ ]:
arVal[0] = 'python'
arVal

['python', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
arVal[0][2]

't'

In [ ]:
arVal[0] = 'python programming'
arVal

['python programming', [1.0, 2.0, 3.14, 4.2, 5.1], [1.0, 2.0, 3.14, 4.2, 5.1]]

In [ ]:
import numpy as np
arData = np.array([1.0, 2.0, 3.14, 4.2, 5.1])
arData

array([1.  , 2.  , 3.14, 4.2 , 5.1 ])

In [ ]:
arData.sum()

15.44

In [ ]:
arVal.sum()

AttributeError: 'list' object has no attribute 'sum'

In [ ]:
print(type(arVal))
print(type(arData))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arData.std()

1.4717934637713266

In [ ]:
arData.cumsum()

array([ 1.  ,  3.  ,  6.14, 10.34, 15.44])

In [ ]:
arData * 2

array([ 2.  ,  4.  ,  6.28,  8.4 , 10.2 ])

In [ ]:
arData ** 2

array([ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ])

In [ ]:
np.sqrt(arData)

array([1.        , 1.41421356, 1.77200451, 2.04939015, 2.25831796])

In [ ]:
arVal = np.array([arData, arData ** 2])
arVal

array([[ 1.    ,  2.    ,  3.14  ,  4.2   ,  5.1   ],
       [ 1.    ,  4.    ,  9.8596, 17.64  , 26.01  ]])

In [ ]:
arVal.sum(axis=0)

array([ 2.    ,  6.    , 12.9996, 21.84  , 31.11  ])

In [ ]:
arVal.sum(axis=1)

array([15.44  , 58.5096])

In [ ]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arZero = np.zeros((2,3), dtype = 'i') 
arZero

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
import pandas as pd

pandas_series = pd.Series([30, 20, 10], index=['국어', '영어', '수학'])
print(type(pandas_series))
pandas_series

<class 'pandas.core.series.Series'>


국어    30
영어    20
수학    10
dtype: int64

In [ ]:
pandas_series[1:]

영어    20
수학    10
dtype: int64

In [ ]:
pandas_series[0]

30

In [ ]:
pandas_series[0][1]

IndexError: invalid index to scalar variable.

In [ ]:
df = pd.DataFrame([30,20,10], columns=['score'], index=['국어', '영어', '수학'])
df

score
국어     30
영어     20
수학     10

In [ ]:
df.index

Index(['국어', '영어', '수학'], dtype='object')

In [ ]:
df.columns

Index(['score'], dtype='object')

In [ ]:
df.loc['국어']

score    30
Name: 국어, dtype: int64

In [ ]:
df.sum()

score    60
dtype: int64

In [ ]:
df.score ** 2

국어    900
영어    400
수학    100
Name: score, dtype: int64

In [ ]:
df['score2'] = (50, 50, 50)
df

score  score2
국어     30      50
영어     20      50
수학     10      50

In [ ]:
df['score2'] = pd.DataFrame([90,90,90], index=['국어', '영어', '수학'])
df

score  score2
국어     30      90
영어     20      90
수학     10      90

In [ ]:
del df['score']

In [ ]:
df['score2'] = (90, 90, 90, 100)

ValueError: Length of values (4) does not match length of index (3)

In [ ]:
df['score2'] = pd.DataFrame([90, 90, 90, 100], index=['국어', '영어', '수학', '윤리'])
df

score2
국어      90
영어      90
수학      90

In [ ]:
df1 = pd.DataFrame([1, 2, 3], columns = ['A'])
df2 = pd.DataFrame([10, 11, 12, 13], columns = ['B'])

df = df1.join(df2, how='outer')
df

A   B
0  1.0  10
1  2.0  11
2  3.0  12
3  NaN  13

In [ ]:
df_inner = df1.join(df2, how='inner')
df_inner

A   B
0  1  10
1  2  11
2  3  12

In [ ]:
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0  1.015472  0.193973 -1.440323  0.284855 -0.103131
1  0.603695 -0.821081 -0.209483  1.234811 -0.844049
2 -0.467288  0.426761 -1.517056 -0.272533  0.474389
3  1.240497  0.223213 -0.285995  0.258394  0.599426
4 -1.135283 -0.437805 -0.869101  0.729745  0.741182

In [ ]:
df.max()

A    1.240497
B    0.426761
C   -0.209483
D    1.234811
E    0.741182
dtype: float64

In [ ]:
df.min()

A   -1.135283
B   -0.821081
C   -1.517056
D   -0.272533
E   -0.844049
dtype: float64

In [ ]:
df.mean()

A    0.251418
B   -0.082988
C   -0.864392
D    0.447054
E    0.173563
dtype: float64

In [ ]:
df.std()

A    1.015582
B    0.524640
C    0.616672
D    0.565726
E    0.653097
dtype: float64

In [ ]:
df.cumsum()

A         B         C         D         E
0  1.015472  0.193973 -1.440323  0.284855 -0.103131
1  1.619166 -0.627107 -1.649806  1.519666 -0.947180
2  1.151878 -0.200347 -3.166862  1.247133 -0.472791
3  2.392375  0.022866 -3.452857  1.505527  0.126634
4  1.257092 -0.414939 -4.321958  2.235272  0.867816

In [ ]:
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.251418 -0.082988 -0.864392  0.447054  0.173563
std    1.015582  0.524640  0.616672  0.565726  0.653097
min   -1.135283 -0.821081 -1.517056 -0.272533 -0.844049
25%   -0.467288 -0.437805 -1.440323  0.258394 -0.103131
50%    0.603695  0.193973 -0.869101  0.284855  0.474389
75%    1.015472  0.223213 -0.285995  0.729745  0.599426
max    1.240497  0.426761 -0.209483  1.234811  0.741182

In [ ]:
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0  1.015472  0.193973 -1.440323  0.284855 -0.103131        X
1  0.603695 -0.821081 -0.209483  1.234811 -0.844049        Y
2 -0.467288  0.426761 -1.517056 -0.272533  0.474389        X
3  1.240497  0.223213 -0.285995  0.258394  0.599426        Y
4 -1.135283 -0.437805 -0.869101  0.729745  0.741182        Z

In [ ]:
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X         0.274092  0.310367 -1.478690  0.006161  0.185629
Y         0.922096 -0.298934 -0.247739  0.746602 -0.122312
Z        -1.135283 -0.437805 -0.869101  0.729745  0.741182